[package]
name = "impatience"
version = "0.0.0"
authors = ["Phlopsi <nbphobos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(loom)'.dependencies]
loom = { path = "../loom-0.3.6" }
